#!/bin/bash
set -e

mkdir -p -m 755 /var/run/apt-cacher-ng
chown apt-cacher-ng:apt-cacher-ng /var/run/apt-cacher-ng

chown -R apt-cacher-ng:root /var/cache/apt-cacher-ng
chmod 777 /var/cache/apt-cacher-ng

exec sudo -u apt-cacher-ng -H /usr/sbin/apt-cacher-ng -c /etc/apt-cacher-ng
