#!/bin/bash
set -e

# generate a password for root.
ROOT_PASSWORD=$(pwgen -c -n -1 12)
echo "root:$ROOT_PASSWORD" | chpasswd
echo User: root Password: $ROOT_PASSWORD

# start supervisord
/usr/bin/supervisord
supervisorctl start sshd

appStart () {
	chown -R apt-cacher-ng:apt-cacher-ng /var/cache/apt-cacher-ng
	chmod 777 /var/cache/apt-cacher-ng
	supervisorctl start apt-cacher-ng

	touch /var/log/apt-cacher-ng/apt-cacher.log
	tail -F /var/log/apt-cacher-ng/apt-cacher.log
}

appHelp () {
	echo "Available options:"
	echo " app:start          - Start apt-cacher-ng and watch the logs (default)"
	echo " app:help           - Displays the help"
	echo " [command]          - Execute the specified linux command eg. bash."
}

case "$1" in
	app:start)
		appStart
		;;
	app:help)
		appHelp
		;;
	*)
		if [ -x $1 ]; then
			$1
		else
			prog=$(which $1)
			if [ -n "${prog}" ] ; then
				shift 1
				$prog $@
			else
				appHelp
			fi
		fi
		;;
esac

exit 0
