#!/bin/bash
set -e

# start supervisord
/usr/bin/supervisord

chown -R apt-cacher-ng:apt-cacher-ng /var/cache/apt-cacher-ng
chmod 777 /var/cache/apt-cacher-ng
supervisorctl start apt-cacher-ng

touch /var/log/apt-cacher-ng/apt-cacher.log
tail -F /var/log/apt-cacher-ng/apt-cacher.log
