#!/bin/bash
set -e

chown -R apt-cacher-ng:apt-cacher-ng /var/cache/apt-cacher-ng
chmod 777 /var/cache/apt-cacher-ng
/usr/sbin/apt-cacher-ng -c /etc/apt-cacher-ng foreground=0

touch /var/log/apt-cacher-ng/apt-cacher.log
tail -F /var/log/apt-cacher-ng/apt-cacher.log
